blank_issues_enabled: true

contact_links:
  - name: 💬 Webinix Community Support
    url: https://github.com/webinix-dev/webinix/discussions
    about: Please can ask and answer questions about Webinix here.
